# **LAB** **ASSESSMENT** **-** **2**

NAME: **Shubham Tejani**


## Question-1
Write a program to perform the following operations on complex numbers.


In [ ]:
def addComplex( z1, z2):
    return z1 + z2
def subComplex( z1, z2):
	return z1-z2
def mulComplex(z1, z2):
	return z1*z2
def compareComplex( z1, z2):
  if z1 != z2:
    return 'Not Equal'
  else: 
    return 'Equal'
# driver program
z1 = complex(2, 3)
z2 = complex(1, 2)
print('Addition is:',addComplex(z1,z2))
print( "Subtraction is : ", subComplex(z1, z2))
print( "Multiplication is : ", mulComplex(z1, z2))
print( "Complex numbers are: ", compareComplex(z1, z2))
a=abs(z1)
b=abs(z2)
print('Check if C1>=C2',a>=b)
print('Check if C1<=C2',a<=b)

Addition is: (3+5j)
Subtraction is :  (1+1j)
Multiplication is :  (-4+7j)
Complex numbers are:  Not Equal
Check if C1>=C2 True
Check if C1<=C2 False


## Question-2
 Write Python program to create a Python class named Circle constructed by a radius and two
methods which will compute the area and the perimeter of a circle. Access the methods and
variables with the object of class Circle

In [ ]:
class Circle():
    def __init__(self, r):
        self.radius = r

    def area(self):
        return self.radius**2*3.14
    
    def perimeter(self):
        return 2*self.radius*3.14

NewCircle = Circle(8)
print(NewCircle.area())
print(NewCircle.perimeter())

200.96
50.24


## Question-3
 Create a Python class named Rectangle constructed by a length and width and a method which
will compute the area of a rectangle. Access the methods and variables with the object of class

In [ ]:
class Rectangle():
    def __init__(self, l, w):
        self.length = l
        self.width  = w

    def rectangle_area(self):
        return self.length*self.width

newRectangle = Rectangle(12, 10)
print(newRectangle.rectangle_area())

120


## Question-4
Define a class called Address that has two attributes: number and street name. Make sure you
have an __init__ method that initializes the object appropriately. You do not need to define
any other methods

In [ ]:
class Address:
	def __init__(self, street, num):
		self.street_name = street
		self.number = num

## Question-5
For this exercise, we want you to describe a generic superclass and at least three subclasses of
that superclass, listing at least two attributes that each class would have. Remember what
classes will inherit (will subclasses inherit attributes from their parent class? Will parent classes
inherit from their subclasses? Will subclasses that share a parent inherit from one another? Be
sure you’re clear on this before continuing with this exercise.) It’s easiest to simply describe a
real-world object.

In [ ]:
class School:
    def __init__(self, name, no_of_students):
        self.name = name
        self.no_of_students = no_of_students
    
    def print(self):
        print(f'\nInstitute Name: {self.name}')
        print(f'No. Of Students: {self.no_of_students}')

class PreSchool(School):
    def __init__(self, name, no_of_students, no_of_teachers, highest_grade):
        super().__init__(name, no_of_students)
        self.no_of_teachers = no_of_teachers
        self.highest_grade = highest_grade
    
    def print(self):
        super().print()
        print(f'Starting Class: {self.no_of_teachers}')
        print(f'Final Class: {self.highest_grade}')

class HighSchool(School):
    def __init__(self, name, no_of_students, no_of_teachers, highest_grade):
        super().__init__(name, no_of_students)
        self.no_of_teachers = no_of_teachers
        self.highest_grade = highest_grade
    
    def print(self):
        super().print()
        print(f'No. of Teachers: {self.no_of_teachers}')
        print(f'Final Class: {self.highest_grade}')

class College(School):
    def __init__(self, name, no_of_students, no_of_courses, no_of_faculties):
        super().__init__(name, no_of_students)
        self.no_of_courses = no_of_courses
        self.no_of_faculties = no_of_faculties
    
    def print(self):
        super().print()
        print(f'No. Of Faculties: {self.no_of_faculties}')
        print(f'No. Of Courses: {self.no_of_courses}')


# Driver Code
hills_nursery = PreSchool("Mindseed", 1500, -3, -1)
hills_nursery.print()

dps = HighSchool("Christ Convent School", 5000, 1, 12)
dps.print()

vit = College("MGM Institute Of Technology", 12000, 18, 350)
vit.print()



Institute Name: Mindseed
No. Of Students: 1500
Starting Class: -3
Final Class: -1

Institute Name: Christ Convent School
No. Of Students: 5000
No. of Teachers: 1
Final Class: 12

Institute Name: MGM Institute Of Technology
No. Of Students: 12000
No. Of Faculties: 350
No. Of Courses: 18


## Question-6
Write a Python program to create a Person class

a) without any variables and methods

b) with name and valid_id as instance attributes. Also, according to your choice two class
variables.

c) define two class methods as per your choice.

d) create a child class Student that will inherit all of the variables and methods of class “Person”. Also, define its own variables and methods.

In [ ]:
class Person:
    def __init__(self, name, valid_id):
        self.name = name
        self.valid_id = valid_id

    def print(self):
        print(f'\nName: {self.name}')
        print(f'Valid ID: {self.valid_id}')

class Student(Person):
    def __init__(self, name, valid_id, age):
        super().__init__(name, valid_id)
        self.age = age

    def print(self):
        super().print()  
        print(f'Age: {self.age}')

    def change_age(self, age):
        self.age = age

    def change_name(self, name):
        self.name = name
    
# Driver Code
student = Student("Priya Kapoor", "202232123", "18")
student.print()

student.change_age(19)
student.change_name("Riya Kapoor")
student.print()


Name: Priya Kapoor
Valid ID: 202232123
Age: 18

Name: Riya Kapoor
Valid ID: 202232123
Age: 19


##Question-7
Write a Python class named Student with two instances student1, student2 and assign given
values to the said instances attributes. Print all the attributes of student1, student2 instances
with their values in the given format.

In [ ]:
class Student:
    school = 'IT'
    address = '201,Vashi,Navi Mumbai' 
student1 = Student()
student2 = Student() 
student1.student_id = "20BAI10152"
student1.student_name = "Ranveer Beck"
student2.student_id = "20BAI10149"
student2.marks_language = 85
student2.marks_science = 93
student2.marks_math = 95 
students = [student1, student2]
for student in students:
    print('\n')
    for attr in student.__dict__:
        print(f'{attr} -> {getattr(student, attr)}')



student_id -> 20BAI10152
student_name -> Ranveer Beck


student_id -> 20BAI10149
marks_language -> 85
marks_science -> 93
marks_math -> 95


##Question-8
Create a Class “Animal” and implement multiple inheritance with two child classes “Horse”,
“Cow”. Define a property that must have the same value for every class instance (object).
Create three instance variable in the base class. Only create the child classes, no need to define
them.


In [ ]:
class Animal:
    def __init__(self, type, name, color, age):
        self.type = type
        self.name = name
        self.color = color
        self.age = age

    def print(self):
        print(f'Type: {self.type}, Name: {self.name}, Color: {self.color}, Age: {self.age}')
    
class Horse(Animal):
    pass

class Cow(Animal):
    pass

class Sheep(Animal):
    pass

horse = Horse("Domestic", "Horse", "Black", 12)
horse.print()

cow = Cow("Domestic", "Cow", "White", 5)
cow.print()

Type: Domestic, Name: Horse, Color: Black, Age: 12
Type: Domestic, Name: Cow, Color: White, Age: 5


##Question-9
What will be the output of the following Python code?

In [ ]:
class Test:
  def __init__(self):
    self.x = 1
  def x_value(self):
    self.x = 10
  
class Test_derived(Test):
  def x_value(self):
    self.x=self.x+1
    return self.x
    
def main():
  obj = Test_derived()
  print(obj.x_value())
  
main()

2


## Question-10
Write a program in python to do matrix multiplication, addition and subtraction

In [ ]:
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

print('Multiplication of two matrix')
result = [[0, 0],
        [0, 0]]
 
# iterating by row of A
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[0])):
 
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
 
for r in result:
    print(r) 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Multiplication of two matrix
[16, 19]
[36, 43]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


##Question-11
Write a Python program to add member(s) in a set.


In [ ]:
lover = {"Meet","Geet"}
print(lover)
lover.add("Preet")
print("Add single element : ",lover)
lover.update(["Ranjeet", "Sangeet"])
print("Add multiple items : ",lover)

{'Geet', 'Meet'}
Add single element :  {'Preet', 'Geet', 'Meet'}
Add multiple items :  {'Preet', 'Geet', 'Meet', 'Ranjeet', 'Sangeet'}


## Question-12
Write a Python program to remove item(s) from a given set.
num_set = set([0, 1, 3, 4, 5])


In [ ]:
num_set = set([0, 1, 3, 4, 5])
print("Original set:")
print(num_set)
num_set.pop()
print("\nAfter removing the first element from the said set:")
print(num_set)

Original set:
{0, 1, 3, 4, 5}

After removing the first element from the said set:
{1, 3, 4, 5}


## Question-13
Write a Python program to multiply all the items in a list.

In [ ]:
# Python program to multiply all values in the
# list using traversal

def multiplyList(myList) :
	
	# Multiply elements one by one
	result = 1
	for x in myList:
		result = result * x
	return result
	
# Driver code
list1 = [1, 2, 3]
list2 = [3, 2, 4]
print(multiplyList(list1))
print(multiplyList(list2))

6
24


## Question-14
 Write a Python program to get the largest number from a list.

In [ ]:
# Python program to find largest
# number in a list

# list of numbers
list1 = [10, 20, 4, 45, 1011]

# sorting the list
list1.sort()

# printing the last element
print("Largest element is:", list1[-1])

Largest element is: 1011


##Question-15
Write a Python program to get the smallest number from a list.

In [ ]:
# Python program to find smallest
# number in a list

# list of numbers
list1 = [10, 20, 15, 45, 99]

# sorting the list
list1.sort()

# printing the first element
print("Smallest element is:", *list1[:1])

Smallest element is: 10
